name: Publish NDM-web to Docker Registry
on: push
      
jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run
      run: git pull origin master
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:    
        github_token: ${{ secrets.GITHUB_TOKEN }}
