language: csharp
mono: none
sudo: required
os: osx

jobs:
  include:
    - stage: rocksdb test   
      script: |
        asdadsdssd
      name: "RocksDB OSX Build"
    - script: 
      - git submodule update --init src/Dirichlet src/rocksdb-sharp
      - if [ $TRAVIS_PULL_REQUEST != false ] || [ $TRAVIS_BRANCH == "master" ]; then
          dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*" src/Nethermind/Nethermind.AuRa.Test;
        else 
          dotnet test -c Release src/Nethermind/Nethermind.AuRa.Test; 
        fi
      name: "Nethermind.AuRa.Test"