language: csharp
mono: none
sudo: required
os: osx
dotnet: 3.0.100
env:

jobs:
  include:
    # - script: dotnet test -c Release src/Nethermind/Ethereum.VM.Test
    #  name: "Ethereum.VM.Test"
    - stage: Nethermind Tests    
      script: 
      - brew install gmp && brew install snappy && brew install lz4 && brew install zstd
      - brew update
      - brew upgrade
      - git clone https://github.com/NethermindEth/nethermind --recursive
      - cd nethermind/src/Nethermind
      - dotnet build Nethermind.sln -c Release
      - cd Nethermind.Runner
      - dotnet run -c Release --no-build -- --config mainnet