name: Alpine Test

on:
  push:
    branches:
    - master

jobs:
  bls-building:
    name: Building bls
    runs-on: ubuntu-latest
    steps:
    - name: Cloning required repositories
      run: |
        git clone git://github.com/alpinelinux/alpine-chroot-install.git
    - name: Install Alpine chroot
      run: |
        cd alpine-chroot-install/
        sudo ./alpine-chroot-install -d /alpine -p build-base -p snappy -p zstd-dev -p lz4-dev -p zlib-dev -p git
    - name: Building RocksDB for Alpine Linux
      run: |
        /alpine/enter-chroot uname -a
        /alpine/enter-chroot env
        /alpine/enter-chroot -u $USER ls
        /alpine/enter-chroot -u $USER git clone https://github.com/facebook/rocksdb.git
        /alpine/enter-chroot -u $USER cd rocksdb/
        /alpine/enter-chroot -u $USER git fetch --tags
        /alpine/enter-chroot -u $USER latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        /alpine/enter-chroot -u $USER git checkout $latestTag
        /alpine/enter-chroot -u $USER TAG="${latestTag:1}"
        /alpine/enter-chroot -u $USER make shared_lib
        /alpine/enter-chroot -u $USER strip librocksdb.so.${TAG}
        /alpine/enter-chroot -u $USER mv librocksdb.so.${TAG} librocksdb.so
