name: Publish NDM-web to Docker Registry
on: 
  push:
    branches: 
      - master
      
jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      run: docker build -t nethermind-rocksdb .
    - name: Run docker container and copy librocksdb file
      run: |
        docker run -d -it --name nethermind-rocksdb nethermind-rocksdb
        docker cp nethermind-rocksdb:/usr/lib/librocksdb.so .
        ls
        pwd
    - uses: actions/upload-artifact@v1
      name: Uploading Alpine Linux artifact
      with:
        name: alpine_linux_artifact_rocksdb
        path: librocksdb.so

