name: Alpine Test

on:
  push:
    branches:
    - master

jobs:
  bls-building:
    name: Building bls
    runs-on: ubuntu-latest
    steps:
    - name: Cloning required repositories
      run: |
        git clone git://github.com/alpinelinux/alpine-chroot-install.git
    - name: Install Alpine chroot
      run: |
        cd alpine-chroot-install/
        sudo ./alpine-chroot-install -d /alpine -p build-base -p snappy -p zstd-dev -p lz4-dev -p zlib-dev -p git
    - name: Building RocksDB for Alpine Linux
      run: |
        /alpine/enter-chroot uname -a
        /alpine/enter-chroot git clone https://github.com/facebook/rocksdb.git
        /alpine/enter-chroot cd rocksdb/
        /alpine/enter-chroot make shared_lib
        /alpine/enter-chroot strip librocksdb.so.${TAG}
        /alpine/enter-chroot mv librocksdb.so.${TAG} librocksdb.so
        /alpine/enter-chroot ls


