name: Publish NDM-web to Docker Registry
on: push
      
jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:    
        pr_title: "docs"
        pr_body: |
          ":crown: *An automated PR* 
          New BLS library has been built.
          - Please upload the new library file to it's destination folder in Nethermind repo"
        pr_label: "documentation"
        github_token: ${{ secrets.GITHUB_TOKEN }}
