name: Alpine Test

on:
  push:
    branches:
    - master

jobs:
  bls-building:
    name: Building bls
    runs-on: ubuntu-latest
    steps:
    - name: Cloning required repositories
      run: |
        git clone git://github.com/alpinelinux/alpine-chroot-install.git
    - name: Install Alpine chroot
      run: |
        cd alpine-chroot-install/
        sudo ./alpine-chroot-install -d /alpine -p build-base -p libsnappy-dev -p libzstd-dev -p liblz4-dev -p zlib1g-dev
    - name: Setting user
      run: |
        /alpine/enter-chroot uname -a
        /alpine/enter-chroot env
        /alpine/enter-chroot -u $USER env
    - name: Building RocksDB for Alpine Linux
      run: |
        git clone https://github.com/facebook/rocksdb.git
        cd rocksdb/
        git fetch --tags
        latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $latestTag
        TAG="${latestTag:1}"
        make shared_lib
        strip librocksdb.so.${TAG}
        mv librocksdb.so.${TAG} librocksdb.so
