name: secp256k1 armv6

on: push
    
jobs:
  arm64_building:
    runs-on: ubuntu-18.04
    name: Build on secp ARM32
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - uses: uraimo/run-on-arch-action@v1.0.5
      id: runcmd
      with:
        architecture: armv6
        distribution: buster
        run: |
          uname -a
          apt-get update && apt-get install docker.io -y
          apt-get install autoconf libtool
          cd secp256k1/
          ./autogen.sh
          ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
          make
          strip .libs/libsecp256k1.so