name: Publish Arm64 Image to Docker Registry
on: push

jobs:
  arm64_building:
    runs-on: ubuntu-18.04
    name: Build on ARM64
    steps:
      - uses: actions/checkout@v2-beta
      - uses: uraimo/run-on-arch-action@v1.0.5
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            uname -a
            apt-get update && apt-get install docker.io -y
      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          GIT_COMMIT: $(git log -1 --format=%h)
        with:
          name: nethermindeth/nethermind-arm32
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build-args: GIT_COMMIT
          dockerfile: Dockerfile_arm32