name: rocksdb armv6

on: push
    
jobs:
  arm64_building:
    runs-on: ubuntu-18.04
    name: Build on rocksdb ARM32
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - uses: uraimo/run-on-arch-action@v1.0.5
      id: runcmd
      with:
        architecture: armv6
        distribution: buster
        run: |
          sudo apt-get update && sudo apt-get install git binutils make libsnappy-dev libzstd-dev liblz4-dev zlib1g-dev
          git clone https://github.com/facebook/rocksdb.git
          cd rocksdb/
          git fetch --tags
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $latestTag
          TAG="${latestTag:1}"
          PORTABLE=1 make shared_lib
          strip librocksdb.so.${TAG}
          mv librocksdb.so.${TAG} librocksdb.so
          pwd
    - uses: actions/upload-artifact@v1
      name: Uploading Artifact
      with: 
        name: artifact_rocksdb
        path: rocksdb/librocksdb.so