name: secp256k1 armv6

on: push
    
jobs:
  arm64_building:
    runs-on: ubuntu-18.04
    name: Build on secp ARM32
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - uses: uraimo/run-on-arch-action@v1.0.5
      id: runcmd
      with:
        architecture: armv7
        distribution: buster
        run: |
          uname -a
          sudo apt-get update
          sudo apt-get install git automake make libtool -y
          git clone https://github.com/NethermindEth/secp256k1
          cd secp256k1/
          ./autogen.sh --disable-dependency-tracking
          ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
          make
          strip .libs/libsecp256k1.so
    - uses: actions/upload-artifact@v1
      name: Uploading Artifact
      with:
        name: artifact_secp256k1
        path: secp256k1/.libs/libsecp256k1.so