name: secp256k1 armv6

on: push
    
jobs:
  arm64_building:
    runs-on: ubuntu-18.04
    name: Build on secp ARM32
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - uses: uraimo/run-on-arch-action@v1.0.5
      id: runcmd
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: |
          uname -a
          apt-get update && add-apt-repository ppa:ubuntu-toolchain-r/test && apt-get install gcc-multilib g++-multilib autoconf libtool -y
          git clone https://github.com/bitcoin-core/secp256k1.git
          cd secp256k1/
          ./autogen.sh
          ./configure --host=i686-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32" --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
          make
          strip .libs/libsecp256k1.so