name: arm64 test
on: 
  push:
    branches: 
      - master

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARM64 
    steps:
      - uses: actions/checkout@v2-beta
      - name: Publish to Docker
        run: |
          ls -al