name: arm64 test
on: 
  push:
    branches: 
      - master

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARM64 
    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
      - uses: uraimo/run-on-arch-action@v1.0.5
        id: runcmd
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            uname -a
            apt-get update && apt-get install autoconf libtool git make docker.io binutils build-essential libgflags-dev libsnappy-dev libzstd-dev liblz4-dev zlib1g-dev -y
            git clone https://github.com/bitcoin-core/secp256k1.git
            cd secp256k1/
            ./autogen.sh
            ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
            make
            strip .libs/libsecp256k1.so.0.0.0
            ldd li
            cd ..
            git clone --recursive https://github.com/NethermindEth/nethermind
            mkdir nethermind/src/Nethermind/Nethermind.Secp256k1/runtimes/linux-arm64
            mkdir nethermind/src/Nethermind/Nethermind.Secp256k1/runtimes/linux-arm64/native/
            mv secp256k1/.libs/libsecp256k1.so.0.0.0 nethermind/src/Nethermind/Nethermind.Secp256k1/runtimes/linux-arm64/native/libsecp256k1.so
            cp Dockerfile nethermind/Dockerfile
            git clone https://github.com/facebook/rocksdb.git
            cd rocksdb/
            git fetch --tags
            latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
            git checkout $latestTag
            TAG="${latestTag:1}"
            make shared_lib
            strip librocksdb.so.${TAG}
            mv librocksdb.so.${TAG} nethermind/src/Nethermind/Nethermind.Secp256k1/runtimes/linux-arm64/native/librocksdb.so
      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          GIT_COMMIT: $(git log -1 --format=%h)
        with:
          name: nethermindeth/nethermind-arm64
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build-args: GIT_COMMIT
          workdir: nethermind
          dockerfile: Dockerfile