name: BLS test

on:
  push:
    branches:
    - master

jobs:
  neth-tests:
    name: bls
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Cloning required repositories
      run: |
        git clone git://github.com/NethermindEth/bls.git
        git clone git://github.com/herumi/mcl.git
    #- name: Installing GMP for ubuntu
    #  if: matrix.os == 'ubuntu-latest'
    #  run: |
    #    sudo apt install libgmp-dev
    #- name: Installing GMP for osx
    #  if: matrix.os == 'macOS-latest'
    #  run: |
    #    brew install gmp
    - name: Cloning lib for Windows
      if: matrix.os == 'windows-latest'
      run: |
        git clone git://github.com/herumi/cybozulib_ext.git
    - name: Building BLS for Windows
      if: matrix.os == 'windows-latest'
      run: |
        Invoke-Webrequest -uri "https://download.visualstudio.microsoft.com/download/pr/9fcc1f0c-c63f-4424-bc46-7351a59fba06/1ed7863dc633c57c42a88c5cef907048/vs_community.exe" -OutFile vs_community.exe
        dir
        ./vs_community.exe --allWorkloads --includeOptional --quiet -installPath "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
        choco install visualcpp-build-tools --params "'/IncludeOptional'"
        dir
        where cl.exe
        cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\"
        dir
        cd "C:\Program Files (x86)\Microsoft Visual Studio\"
        dir
        D:\a\rpc-diagnosis-tool\rpc-diagnosis-tool\bls\mklib.bat dll
        D:\a\rpc-diagnosis-tool\rpc-diagnosis-tool\bls\mk.bat -d test\bls_c384_test.cpp
        D:\a\rpc-diagnosis-tool\rpc-diagnosis-tool\bls\bin\bls_c384_test.exe
    #- name: Building BLS for Linux
    #  if: matrix.os == 'ubuntu-latest'
    #  run: |
    #    cd bls/
    #   make test
    #- name: Building BLS for OSX
    #  if: matrix.os == 'macOS-latest'
    #  run: |
    #    cd bls/
    #    make all


