name: RocksDB Build TEST

on:
  push:
    branches:
    - master

jobs:
  rocksb-building:
    name: Building RocksDB
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
    - name: Cloning rocksDB repository
      run: |
        git clone git://github.com/warrenfalk/rocksdb-sharp-native.git
    - name: Building rocksDB for Windows
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        call "C:\Program Files\Git\bin\bash.exe"
        sed -i '28s/ROCKSDBVNUM=`cat rocksdbversion`/ROCKSDBVNUM=6.4.6/' /d/a/rpc-diagnosis-tool/rpc-diagnosis-tool/rocksdb-sharp-native/build-rocksdb.sh
        sh /d/a/rpc-diagnosis-tool/rpc-diagnosis-tool/rocksdb-sharp-native/build-rocksdb.sh
        cd /d/a/rpc-diagnosis-tool/rpc-diagnosis-tool/rocksdb-sharp-native/build/ && ls 
      shell: cmd
    - name: Building rocksDB for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libsnappy-dev libzstd-dev liblz4-dev zlib1g-dev
        cd rocksdb-sharp-native/
        echo 6.4.6 > rocksdbversion 
        ./build-rocksdb.sh
    - name: Building rocksDB for OSX
      if: matrix.os == 'macOS-latest'
      run: |
        git clone git://github.com/Cyan4973/lz4.git
        curl https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.13_for_Xcode_9.4/Command_Line_Tools_macOS_10.13_for_Xcode_9.4.dmg -o Command_Line_Tools_macOS_10.13_for_Xcode_9.4.dmg
        sudo hdiutil attach Command_Line_Tools_macOS_10.13_for_Xcode_9.4.dmg
        cd /Volumes/Command_Line_Tools_macOS_10.13_for_Xcode_9.4
        sudo cp -rf Xcode9.4.app /Applications
        sudo hdiutil detach /Volumes/Command_Line_Tools_macOS_10.13_for_Xcode_9.4
        brew install gcc
        brew install snappy
        brew install zstd
        make -C lz4/lib
        cp -L lz4/lib/liblz4.dylib ./liblz4_64.dylib
        make -C lz4/lib clean
        CFLAGS="-arch i386" CXXFLAGS="-arch i386" LDFLAGS="-arch i386" make -C lz4/lib
        cp -L lz4/lib/liblz4.dylib ./liblz4_32.dylib
        lipo -create ./liblz4_32.dylib ./liblz4_64.dylib -output ./liblz4.dylib
        cp -v ./liblz4.dylib lz4/lib/$(readlink lz4/lib/liblz4.dylib)
        touch lz4/lib/liblz4
        make -C lz4/lib install
        sh build-rocksdb.sh