name: RocksDB Build TEST

on:
  push:
    branches:
    - master

jobs:
  rocksb-building:
    name: Building RocksDB
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
    - name: Cloning rocksDB repository
      run: |
        git clone git://github.com/warrenfalk/rocksdb-sharp-native.git
    - name: Building rocksDB for Windows
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        call "C:\Program Files\Git\bin\bash.exe"
        sed -i '28s/ROCKSDBVNUM=`cat rocksdbversion`/ROCKSDBVNUM=6.4.6/' /d/a/rpc-diagnosis-tool/rpc-diagnosis-tool/rocksdb-sharp-native/build-rocksdb.sh
        sh /d/a/rpc-diagnosis-tool/rpc-diagnosis-tool/rocksdb-sharp-native/build-rocksdb.sh
        cd /d/a/rpc-diagnosis-tool/rpc-diagnosis-tool/rocksdb-sharp-native/build/ && ls 
      shell: cmd
    - name: Building rocksDB for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libsnappy-dev libzstd-dev liblz4-dev zlib1g-dev
        cd rocksdb-sharp-native/
        echo 6.4.6 > rocksdbversion 
        ./build-rocksdb.sh
    - name: Building rocksDB for OSX
      if: matrix.os == 'macOS-latest'
      run: |
        xcode-select --install
        brew install snappy
        cd /Users/runner/runners/2.160.2/work/rpc-diagnosis-tool/rpc-diagnosis-tool/rocksdb-sharp-native/
        echo 6.4.6 > rocksdbversion
        sh build-rocksdb.sh