name: RocksDB Build TEST

on:
  push:
    branches:
    - master

jobs:
  rocksb-building:
    name: Building RocksDB
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Cloning rocksDB repository
      run: |
        git clone git://github.com/warrenfalk/rocksdb-sharp.git
    - name: Building rocksDB for Windows
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd C:\ && dir 
        call "C:\Program Files\Git\bin\bash.exe"
        cd D:\a\rpc-diagnosis-tool\rocksdb-sharp\native-build && call build-rocksdb.sh
      shell: cmd