name: secp256k1 Build TEST2

on:
  push:
    branches:
    - master

jobs:
  rocksb-building:
    name: Building Secp256k1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Cloning secp256k1 repository
      run: |
        git clone https://github.com/bitcoin-core/secp256k1.git
    #- name: Building secp for win
    #  if: matrix.os == 'windows-latest'
    #  run: |
    #    choco install msys2
    #    refreshenv
    #  shell: cmd
    - uses: numworks/setup-msys2@v1
    - name: Building cd
      if: matrix.os == 'windows-latest'
      run: |
        msys2do pacman --noconfirm -S autoconf libtool make automake
    - run: msys2do LC_ALL=C pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}'
    - run: |
        cat <<EOT >> run.sh
        mv secp256k1 64bit
        cd 64bit
        sh autogen.sh 
        echo "LDFLAGS = -no-undefined" >> Makefile.am
        sh configure --host=x86_64-w64-mingw32 --enable-module-recovery --enable-experimental --enable-module-ecdh
        make
        mv .libs/libsecp256k1-0.dll ../secp256k1.dll
        EOT
      shell: bash
    - run: cat run.sh
    - run: msys2do ./run.sh