name: secp256k1 Build TEST2

on:
  push:
    branches:
    - master

jobs:
  rocksb-building:
    name: Building Secp256k1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Cloning secp256k1 repository
      run: |
        git clone https://github.com/bitcoin-core/secp256k1.git
    - name: Building secp for win
      if: matrix.os == 'windows-latest'
      run: |
        choco install msys2
        refreshenv
      shell: cmd
    - name: Building cd
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\tools\msys64\mingw64.exe"
        mv secp256k1 64bit
        cd 64bit
        ./autogen.sh
        echo "LDFLAGS = -no-undefined" >> Makefile.am
        ./configure --host=$1 --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-endomorphism --disable-jni
        make
        mv .libs/libsecp256k1-0.dll ../libsecp256k1.dll
      shell: cmd