name: secp256k1 Build TEST2

on:
  push:
    branches:
    - master

jobs:
  rocksb-building:
    name: Building Secp256k1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Cloning secp256k1 repository
      run: |
        git clone https://github.com/bitcoin-core/secp256k1.git
    #- name: Building secp for win
    #  if: matrix.os == 'windows-latest'
    #  run: |
    #    choco install msys2
    #    refreshenv
    #  shell: cmd
    - uses: numworks/setup-msys2@v1
    - name: Building cd
      if: matrix.os == 'windows-latest'
      run: |
        msys2do 'echo "Y" | pacman -S autoconf libtool make && mv secp256k1 64bit && cd 64bit && sh autogen.sh'
        msys2do echo "LDFLAGS = -no-undefined" >> Makefile.am
        msys2do sh configure --host=x86_64-w64-mingw32 --enable-module-recovery --enable-experimental --enable-module-ecdh
        msys2do make
        msys2do mv .libs/libsecp256k1-0.dll ../secp256k1.dll
      shell: cmd