name: EIP2537 Rust libs Build

# on:
#   repository_dispatch:
#     types: rust_build
on: push

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04
          - arch: armv7
            distro: ubuntu18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.6
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            echo $(uname -a)
            apt-get update
            apt-get install docker.io -y
            docker run nethermindeth/nethermindarm64 --config spaceneth_persistent
