name: Standard Build

on: push

jobs:
  neth-tests:
    name: Nethermind Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-10.13]
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow --progress --prune origin +refs/heads/*:refs/remotes/origin/*
    - name: Updating submodules
      run: git submodule update --init src/Dirichlet src/rocksdb-sharp
    - name: Installing Linux packages
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libsnappy-dev libc6-dev libc6
    - name: Installing macOS packages
      if: matrix.os == 'macOS-10.13'
      run: brew install gmp && brew install snappy && brew install lz4 && brew install zstd
    - name: Run Nethermind
      run: |
        cd nethermind/src/Nethermind
        dotnet build Nethermind.sln -c Release
        cd Nethermind.Runner
        dotnet run -c Release --no-build -- --config mainnet

